-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgETlpk/Qg6chTJlq0
V3RlUB1PJE3yL3N+3bhz1uKkHNqgCgYIKoZIzj0DAQehRANCAATmJQFSekMvF1zv
szt3lykL8PJwVDgTxHj9T4Giy5QSfJlaK0htZryU0q1jaTQyZxUZfpgvPPYiGzew
2ZZvgIb2
-----END PRIVATE KEY-----